dist: bionic

language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make install
  - make lint
  - make test
  - make coverage
  - go test $(shell go list ./... | grep -v /vendor/) -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
